<?php

/****************************************************
 * WARNING                                          *
 *                                                  *
 * This file is written by simple_shortcodes.php    *
 *                                                  *
 * DO NOT EDIT THIS FILE - your edits will be lost! *
 *                                                  *
 ***************************************************/

/*
* Register the shortcodes
*/
if ( function_exists( 'add_shortcode' ) ) {
    add_shortcode('mb_ack', 'mb_ack_shortcode_handler');
}

/**
* mb_ack_shortcode_handler - produces and returns the content to replace the shortcode tag
*
* @param array $atts  An array of attributes passed from the shortcode
* @param string $content   If the shortcode wraps round some html, this will be passed.
*/
function mb_ack_shortcode_handler( $atts , $content = null) {
    //return the content.
    return 'This blog uses <a href=\'http://michael-baker.com/simple_shortcodes/\'>Simple Shortcodes</a> which was initially developed for <a href=\'http://frickers.co.uk/\'>world renowned Marine Artist Gordon Frickers</a>.';
}

?>